### ISSUE TITLE
mailbox tests with a large number of waiting threads

### ISSUE THREAD

**Issue by mlaures** [Radio-Camera-Initiative/rci-memory-lender#19]
- Maybe have a few tests with a large number of waiting threads (and potentially less count checking)?

_Originally posted by @yupinghuang in https://github.com/Radio-Camera-Initiative/rci-memory-lender/pull/14#pullrequestreview-1095409806_

-> questions here: would all threads be able to read the value or do we have some that we expect to wait forever

**Comment by yupinghuang** [comment]
I was thinking the former (as in they should be able to read the value).
